### ISSUE TITLE
Attempts to use mod_readaloud\event\course_module_viewed class

### ISSUE THREAD

**Issue by mudrd8mz** [justinhunt/moodle-mod_wordcards#1]
The report.php file tries to call
```
\mod_readaloud\event\course_module_viewed::create()
```
However, the `mod_readaloud` module is not specified as the dependency and so the fatal error appears:

![image](https://user-images.githubusercontent.com/85831/87425923-c4007f80-c5de-11ea-9ae0-e6c8ae8b6c18.png)

I believe the intention was to have a class `mod_wordcards\event\course_module_viewed` implemented and called.

**Comment by justinhunt** [comment]
Ouch. Thats a bad one. Thanks for catching it. Its fixed up now.
