### ISSUE TITLE
API Privacy

### ISSUE THREAD

**Issue by cedrinetille** [justinhunt/moodle-mod_wordcards#17]
Hi,

I'm doing a security analysis of your plugin for a customer in Europe that wants to install your plugin.

After going through the code, it seems that the requirements from the [privacy API](https://moodledev.io/docs/apis/subsystems/privacy)  has not been implemented. 

https://github.com/justinhunt/moodle-mod_wordcards.git

**Comment by justinhunt** [comment]
Indeed. I can't believe this was not done. I will update this next week . Thanks for the alert.

**Comment by cedrinetille** [comment]
Thanks for fixing it !
