### ISSUE TITLE
Namespace mod_wordcards\report violates the namespace naming guidelines

### ISSUE THREAD

**Issue by mudrd8mz** [justinhunt/moodle-mod_wordcards#2]
Please see https://docs.moodle.org/dev/Coding_style#Rules_for_level2

If you really want to use a dedicated namespace for the reporting features, the namespace should be `mod_wordcards\local\report`

**Comment by justinhunt** [comment]
Thanks.  I moved the reports feature into namespace: mod_wordcards\local\report
