### ISSUE TITLE
thirdpartylibs.xml would be useful to have

### ISSUE THREAD

**Issue by mudrd8mz** [justinhunt/moodle-mod_wordcards#3]
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml would be good to have here. It would allow to keep an overview of all the additional libraries that ship with the plugin and would allow to keep track of their licenses (to make sure they are all compatible with the GPL).

Additionally, as the 3rd party libraries are excluded from coding style checking, it would lead to more relevant CI checks figures.

**Comment by justinhunt** [comment]
Thanks. I added a thirdpartylibs.xml and documented glide.js inside it.
