### ISSUE TITLE
CSS selectors not specific enough 

### ISSUE THREAD

**Issue by mudrd8mz** [justinhunt/moodle-mod_wordcards#6]
Some CSS selectors in the styles file such as `#results`, `#counter` or `#question` are not specific enough for the Wordcards page. As the styles.css are merged from all plugins and served together, the styling present in this file is likely to unexpectedly affect other places in moodle.

Ref: https://docs.moodle.org/dev/Plugin_contribution_checklist#CSS_styles

**Comment by justinhunt** [comment]
Thanks. This is fixed now
